const axios = require('axios');
const cheerio = require('cheerio');

module.exports = async (req, res) => {
    try {
            // 1. Target URL (Testing ke liye safe link taaki 403 block na aaye)
                    const targetUrl = req.query.url || 'https://internshala.com/internships/physiotherapy-internship/';
                            
                                    const response = await axios.get(targetUrl, {
                                                headers: { 
                                                                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' 
                                                                            }
                                                                                    });
                                                                                            
                                                                                                    const $ = cheerio.load(response.data);
                                                                                                            const pageTitle = $('title').text() || 'No Title Found'; 
                                                                                                                    
                                                                                                                            // 2. AI Brain Context (Aapki profile)
                                                                                                                                    const aiPrompt = `You are an expert Medical Career AI Agent. Evaluate this job/search page title: "${pageTitle}". 
                                                                                                                                            The candidate is Dr. Purab Sinha, a Clinical Physiotherapist based in India with experience across orthopedics, neuro-rehabilitation, OPD, and cardiopulmonary wards. He is skilled in manual therapy, therapeutic exercise prescription, and sports trauma management.
                                                                                                                                                    
                                                                                                                                                            Task: Tell me in 2 short bullet points if these types of roles match his profile, and give a "Match Score" out of 100%.`;

                                                                                                                                                                    // 3. Aapki OpenRouter API Key
                                                                                                                                                                            const openRouterKey = process.env.OPENROUTER_API_KEY;
                                                                                                                                                                            
                                                                                                                                                                                    
                                                                                                                                                                                            // AI se Analysis karwana
                                                                                                                                                                                                    const aiResponse = await axios.post("https://openrouter.ai/api/v1/chat/completions", {
                                                                                                                                                                                                                model: "google/gemini-1.5-flash", // Fast model
                                                                                                                                                                                                                            messages: [{ role: "user", content: aiPrompt }]
                                                                                                                                                                                                                                    }, {
                                                                                                                                                                                                                                                headers: {
                                                                                                                                                                                                                                                                "Authorization": `Bearer ${openRouterKey}`,
                                                                                                                                                                                                                                                                                "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    const aiResponseText = aiResponse.data.choices[0].message.content;

                                                                                                                                                                                                                                                                                                                            // 4. Final Output JSON Format mein
                                                                                                                                                                                                                                                                                                                                    res.status(200).json({ 
                                                                                                                                                                                                                                                                                                                                                success: true, 
                                                                                                                                                                                                                                                                                                                                                            job_title: pageTitle,
                                                                                                                                                                                                                                                                                                                                                                        ai_analysis: aiResponseText
                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                            console.error("API Error:", error.message);
                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ success: false, error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                        