const axios = require('axios');
const cheerio = require('cheerio');

module.exports = async (req, res) => {
    try {
            // 1. Target URL (Ab default URL Indeed ka Fresher Physiotherapist search hai)
                    const targetUrl = req.query.url || 'https://in.indeed.com/jobs?q=physiotherapist+fresher&l=India';
                            
                                    const response = await axios.get(targetUrl, {
                                                headers: { 
                                                                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' 
                                                                            }
                                                                                    });
                                                                                            
                                                                                                    const $ = cheerio.load(response.data);
                                                                                                            // Page ka title aur thoda description nikalne ki koshish
                                                                                                                    const pageTitle = $('title').text() || 'No Title Found'; 
                                                                                                                            
                                                                                                                                    // 2. AI Brain Context (Aapki profile ke hisaab se)
                                                                                                                                            const aiPrompt = `You are an expert Medical Career AI Agent. Evaluate this job/search page title: "${pageTitle}". 
                                                                                                                                                    The candidate is Dr. Purab Sinha, a Clinical Physiotherapist based in India with experience across orthopedics, neuro-rehabilitation, OPD, and cardiopulmonary wards. He is skilled in manual therapy, therapeutic exercise prescription, and sports trauma management.
                                                                                                                                                            
                                                                                                                                                                    Task: Tell me in 2 short bullet points if these types of roles match his profile, and give a "Match Score" out of 100%.`;

                                                                                                                                                                            // 👉 YAHAN APNI OPENROUTER API KEY DAALEIN
                                                                                                                                                                                    const openRouterKey = "sk-or-v1-AAPKI_KEY_YAHAN_AAYEGI"; 
                                                                                                                                                                                            
                                                                                                                                                                                                    let aiResponseText = "AI abhi off hai. OpenRouter API Key daalein.";
                                                                                                                                                                                                            
                                                                                                                                                                                                                    // 3. AI Analysis
                                                                                                                                                                                                                            if (openRouterKey !== "sk-or-v1-AAPKI_KEY_YAHAN_AAYEGI") {
                                                                                                                                                                                                                                        const aiResponse = await axios.post("https://openrouter.ai/api/v1/chat/completions", {
                                                                                                                                                                                                                                                        model: "google/gemini-2.5-flash", // Fast & Free
                                                                                                                                                                                                                                                                        messages: [{ role: "user", content: aiPrompt }]
                                                                                                                                                                                                                                                                                    }, {
                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                        "Authorization": `Bearer ${openRouterKey}`,
                                                                                                                                                                                                                                                                                                                                            "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                    aiResponseText = aiResponse.data.choices[0].message.content;
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    // 4. Final Output Vercel par bhejna
                                                                                                                                                                                                                                                                                                                                                                                                            res.status(200).json({ 
                                                                                                                                                                                                                                                                                                                                                                                                                        success: true, 
                                                                                                                                                                                                                                                                                                                                                                                                                                    job_title: pageTitle,
                                                                                                                                                                                                                                                                                                                                                                                                                                                ai_analysis: aiResponseText
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ success: false, error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        