const axios = require('axios');
const cheerio = require('cheerio');

module.exports = async (req, res) => {
    try {
            // 1. Job Scrape Karna
                    const targetUrl = req.query.url || 'https://internshala.com/internships/physiotherapy-internship/';
                            const response = await axios.get(targetUrl, {
                                        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' }
                                                });
                                                        
                                                                const $ = cheerio.load(response.data);
                                                                        const pageTitle = $('title').text(); 
                                                                                
                                                                                        // 2. AI Brain (OpenRouter) ko Context Dena
                                                                                                const aiPrompt = `You are an expert AI Career Agent. Evaluate this job title/opportunity: "${pageTitle}". 
                                                                                                        The candidate is a Clinical Physiotherapist with deep clinical experience across orthopedics, neuro-rehabilitation, outpatient departments (OPD), and cardiopulmonary/ICU wards. They possess advanced competency in manual therapy, therapeutic exercise prescription, gait analysis, and pitch-side acute sports trauma management.
                                                                                                                
                                                                                                                        Task: Tell me in 2 short lines if this role is a good fit for this clinical profile, and give a "Match Score" out of 100%.`;

                                                                                                                                // YAHAN APNI OPENROUTER API KEY DAALEIN 👇
                                                                                                                                        const openRouterKey = "sk-or-v1-AAPKI_KEY_YAHAN_AAYEGI"; 
                                                                                                                                                
                                                                                                                                                        let aiResponseText = "AI analysis skipped. Please add your OpenRouter API Key in the code.";
                                                                                                                                                                
                                                                                                                                                                        // 3. AI se Analysis karwana
                                                                                                                                                                                if (openRouterKey !== "sk-or-v1-AAPKI_KEY_YAHAN_AAYEGI") {
                                                                                                                                                                                            const aiResponse = await axios.post("https://openrouter.ai/api/v1/chat/completions", {
                                                                                                                                                                                                            model: "google/gemini-2.5-flash", // Free & Fast model
                                                                                                                                                                                                                            messages: [{ role: "user", content: aiPrompt }]
                                                                                                                                                                                                                                        }, {
                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                            "Authorization": `Bearer ${openRouterKey}`,
                                                                                                                                                                                                                                                                                                "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                        aiResponseText = aiResponse.data.choices[0].message.content;
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                        // 4. Final Output Vercel par bhejna
                                                                                                                                                                                                                                                                                                                                                                res.status(200).json({ 
                                                                                                                                                                                                                                                                                                                                                                            success: true, 
                                                                                                                                                                                                                                                                                                                                                                                        job_title: pageTitle,
                                                                                                                                                                                                                                                                                                                                                                                                    ai_analysis: aiResponseText
                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ success: false, error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                            